-- ==========================================
-- 1. Blogs Table & Enhancements
-- ==========================================

create table if not exists blogs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  slug text not null unique,
  content text not null,
  excerpt text,
  image_url text,
  published boolean default false,
  author_email text
);

-- Add columns from v2
alter table blogs add column if not exists tags text[] default '{}';
alter table blogs add column if not exists seo_title text;
alter table blogs add column if not exists seo_description text;
alter table blogs add column if not exists views bigint default 0;

-- RLS for Blogs
alter table blogs enable row level security;

drop policy if exists "Public blogs are viewable by everyone" on blogs;
create policy "Public blogs are viewable by everyone"
  on blogs for select
  using ( published = true );

drop policy if exists "Enable insert for authenticated users only" on blogs;
create policy "Enable insert for authenticated users only"
  on blogs for insert
  with check ( true );

drop policy if exists "Enable update for authenticated users only" on blogs;
create policy "Enable update for authenticated users only"
  on blogs for update
  using ( true );

drop policy if exists "Enable delete for authenticated users only" on blogs;
create policy "Enable delete for authenticated users only"
  on blogs for delete
  using ( true );


-- ==========================================
-- 2. Testimonials Table
-- ==========================================

create table if not exists testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text,
  company text,
  content text not null,
  image_url text,
  approved boolean default false
);

-- Add columns from v4
alter table testimonials add column if not exists social_link text;

-- RLS for Testimonials
alter table testimonials enable row level security;

drop policy if exists "Public view approved testimonials" on testimonials;
create policy "Public view approved testimonials"
  on testimonials for select
  using ( approved = true );

drop policy if exists "Admin manage testimonials" on testimonials;
create policy "Admin manage testimonials"
  on testimonials for all
  using ( true );


-- ==========================================
-- 3. Blog Engagement Tables (Comments & Likes)
-- ==========================================

-- Blog Comments
create table if not exists blog_comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  blog_slug text not null references blogs(slug) on delete cascade,
  user_id text not null, -- Clerk User ID
  user_name text not null,
  user_image text,
  content text not null
);

-- Blog Likes
create table if not exists blog_likes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  blog_slug text not null references blogs(slug) on delete cascade,
  user_id text not null, -- Clerk User ID
  unique(blog_slug, user_id) -- One like per user per blog
);

-- RLS for Engagement
alter table blog_comments enable row level security;
alter table blog_likes enable row level security;

-- Policies for Comments
drop policy if exists "Public view comments" on blog_comments;
create policy "Public view comments"
  on blog_comments for select
  using ( true );

drop policy if exists "Authenticated users can comment" on blog_comments;
create policy "Authenticated users can comment"
  on blog_comments for insert
  with check ( true );

drop policy if exists "Users can delete own comments" on blog_comments;
create policy "Users can delete own comments"
  on blog_comments for delete
  using ( true );

-- Policies for Likes
drop policy if exists "Public view likes" on blog_likes;
create policy "Public view likes"
  on blog_likes for select
  using ( true );

drop policy if exists "Authenticated users can like" on blog_likes;
create policy "Authenticated users can like"
  on blog_likes for insert
  with check ( true );

drop policy if exists "Authenticated users can unlike" on blog_likes;
create policy "Authenticated users can unlike"
  on blog_likes for delete
  using ( true );
