-- Create a table for blog posts
create table blogs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  slug text not null unique,
  content text not null,
  excerpt text,
  image_url text,
  published boolean default false,
  author_email text -- to link with Clerk user if needed
);

-- Enable Row Level Security (RLS)
alter table blogs enable row level security;

-- Create a policy that allows anyone to read published blogs
create policy "Public blogs are viewable by everyone"
  on blogs for select
  using ( published = true );

-- Create a policy that allows admins (or authenticated users) to insert/update/delete
-- For simplicity, if you are using the service role key on the server, RLS is bypassed.
-- If using the client key, you'd need a policy checking the user's ID/Email.
-- Example for testing (allow all for now, assuming you secure the WRITE operations on the server side):
create policy "Enable insert for authenticated users only"
  on blogs for insert
  with check ( true );

create policy "Enable update for authenticated users only"
  on blogs for update
  using ( true );

create policy "Enable delete for authenticated users only"
  on blogs for delete
  using ( true );
