-- 1. Create Blog Comments Table
create table if not exists blog_comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  blog_slug text not null references blogs(slug) on delete cascade,
  user_id text not null, -- Clerk User ID
  user_name text not null,
  user_image text,
  content text not null
);

-- 2. Create Blog Likes Table
create table if not exists blog_likes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  blog_slug text not null references blogs(slug) on delete cascade,
  user_id text not null, -- Clerk User ID
  unique(blog_slug, user_id) -- One like per user per blog
);

-- 3. Enable RLS
alter table blog_comments enable row level security;
alter table blog_likes enable row level security;

-- 4. Policies for Comments
-- Anyone can view comments
create policy "Public view comments"
  on blog_comments for select
  using ( true );

-- Authenticated users can insert comments (enforced by app logic + clerk, but good to have)
create policy "Authenticated users can comment"
  on blog_comments for insert
  with check ( true );
  -- In a real prod environment with Supabase Auth, you'd check auth.uid() = user_id
  -- With Clerk, we trust the server action to verify the user before inserting.

-- Users can delete their own comments (again, logic handled in server action for Clerk)
create policy "Users can delete own comments"
  on blog_comments for delete
  using ( true );

-- 5. Policies for Likes
-- Anyone can view likes
create policy "Public view likes"
  on blog_likes for select
  using ( true );

-- Authenticated users can insert/delete likes
create policy "Authenticated users can like"
  on blog_likes for insert
  with check ( true );

create policy "Authenticated users can unlike"
  on blog_likes for delete
  using ( true );
