-- 1. Update Blogs Table
alter table blogs add column if not exists tags text[] default '{}';
alter table blogs add column if not exists seo_title text;
alter table blogs add column if not exists seo_description text;
alter table blogs add column if not exists views bigint default 0;

-- 2. Create Testimonials Table
create table if not exists testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text,
  company text,
  content text not null,
  image_url text,
  approved boolean default false
);

-- 3. Enable RLS for Testimonials
alter table testimonials enable row level security;

-- Public can view APPROVED testimonials
create policy "Public view approved testimonials"
  on testimonials for select
  using ( approved = true );

-- Admin (mocked for now as 'true' since we check on server) can do everything
create policy "Admin manage testimonials"
  on testimonials for all
  using ( true );
